const toggle=document.querySelector('.nav-toggle');toggle.addEventListener('click',()=>{const open=document.querySelector('nav').classList.toggle('open');toggle.setAttribute('aria-expanded',open)});
const products=[['House burger',18,'Food','🍔'],['Garden salad',14,'Food','🥗'],['Margherita pizza',19,'Food','🍕'],['French fries',7,'Food','🍟'],['Iced coffee',5,'Drinks','☕'],['Fresh lemonade',5,'Drinks','🍋']];let order={};
function drawProducts(cat='All'){const el=document.querySelector('#products');if(!el)return;el.replaceChildren();products.forEach((p,i)=>{if(cat!=='All'&&p[2]!==cat)return;const b=document.createElement('button');b.className='product';b.innerHTML=`<span class="food" aria-hidden="true">${p[3]}</span><b>${p[0]}</b><small>$${p[1].toFixed(2)} CAD · Add +</small>`;b.setAttribute('aria-label',`Add ${p[0]} for ${p[1]} Canadian dollars`);b.onclick=()=>{order[i]=(order[i]||0)+1;drawOrder()};el.append(b)})}
function drawOrder(){const el=document.querySelector('#order');if(!el)return;el.innerHTML=Object.entries(order).map(([i,n])=>`<div class="orderline"><span>${n} × ${products[i][0]}</span><b>$${(n*products[i][1]).toFixed(2)}</b></div>`).join('')||'<p class="empty">Choose an item to start your ticket.</p>';el.setAttribute('aria-live','polite');document.querySelector('#total').textContent='$'+Object.entries(order).reduce((s,[i,n])=>s+products[i][1]*n,0).toFixed(2)}
drawProducts();drawOrder();document.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-cat]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');drawProducts(b.dataset.cat)}));document.querySelector('#reset')?.addEventListener('click',()=>{order={};drawOrder()});
const workflows={full:['A table-first service',['Welcome guests and choose a table','Build the order with item notes','Coordinate the kitchen handoff','Review the bill and close the table']],pub:['Built around a busy room',['Open an order at the bar or table','Add food and drink selections','Review changes with the team','Confirm payment requirements']],quick:['A clear path through the counter',['Choose dine-in or takeaway','Build the order at the counter','Send preparation details to the kitchen','Complete the handoff to the guest']]};function setMode(key){const el=document.querySelector('#workflow');if(el){const [title,steps]=workflows[key];el.innerHTML=`<h3>${title}</h3><ol>${steps.map(x=>`<li>${x}</li>`).join('')}</ol>`}}setMode('full');document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-mode]').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-pressed','false')});b.classList.add('active');b.setAttribute('aria-pressed','true');setMode(b.dataset.mode)}));
document.querySelector('#brief')?.addEventListener('submit',e=>{e.preventDefault();if(!validateBrief(e.target))return;const data=new FormData(e.target);const txt=`NEXPLATE — SETUP BRIEF\n\nName: ${data.get('name')}\nRestaurant: ${data.get('restaurant')}\nService style: ${data.get('style')}\nLocations: ${data.get('locations')}\n\nRequirements:\n${data.get('needs')||'To discuss'}`;const url=URL.createObjectURL(new Blob([txt],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='NEXPLATE-setup-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#form-status').textContent='Your brief is ready to download.'});
(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.15});
document.querySelectorAll('.section h2,.sectiontop,.terminal,.tiles article,.flow-step,.restaurant,.cta,.feature,.pricing-card,.faq,.form-layout>*,.kitchen-demo>div').forEach(el=>{const sib=[...el.parentElement.children].filter(x=>x.tagName===el.tagName);Object.getOwnPropertyDescriptor(HTMLElement.prototype,'style').get.call(el).setProperty('--d',Math.min(sib.indexOf(el),5)*.1+'s');el.classList.add('reveal');io.observe(el)});
const ws=document.querySelector('.wordstrip');if(ws){const t=document.createElement('div');t.className='track';t.innerHTML=ws.innerHTML+ws.innerHTML.replace(/<span>ONE CONNECTED SERVICE<\/span>/,'<span>ONE CONNECTED SERVICE</span>');t.innerHTML=ws.innerHTML+'<span>✳</span>'+ws.innerHTML+'<span>✳</span>';ws.replaceChildren(t);ws.classList.add('marquee')}
document.addEventListener('click',e=>{const p=e.target.closest('.product');if(p){p.classList.remove('added');void p.offsetWidth;p.classList.add('added');const t=document.querySelector('#total');t.classList.remove('bump');void t.offsetWidth;t.classList.add('bump')}});})();

/* Reveal panels on scroll; only hide them once JS is running so content stays crawlable and visible without it. */
(()=>{const r=document.querySelectorAll(".panel");if(!r.length)return;if(matchMedia("(prefers-reduced-motion: reduce)").matches||!("IntersectionObserver" in window))return;document.documentElement.classList.add("js-reveal");const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("in");io.unobserve(e.target)}}),{threshold:.2});r.forEach(p=>io.observe(p))})();

/* Accessibility: menu focus handling + inline form errors */
(()=>{const t=document.querySelector('.nav-toggle'),n=document.querySelector('#site-nav');if(!t||!n)return;
const close=r=>{n.classList.remove('open');t.setAttribute('aria-expanded','false');if(r)t.focus()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&n.classList.contains('open'))close(true)});
n.addEventListener('click',e=>{if(e.target.closest('a'))close(false)});
document.addEventListener('click',e=>{if(n.classList.contains('open')&&!n.contains(e.target)&&!t.contains(e.target))close(false)});
matchMedia('(min-width:901px)').addEventListener('change',e=>{if(e.matches)close(false)});})();
function validateBrief(form){const rules=[['name','Enter your name.'],['restaurant','Enter your restaurant’s name.'],['locations','Enter a number of locations between 1 and 10,000.']];let first=null;
rules.forEach(([k,msg])=>{const el=form.elements[k];if(!el)return;let err=form.querySelector('#err-'+k);const bad=!el.value.trim()||(el.type==='number'&&(+el.value<1||+el.value>10000||!Number.isFinite(+el.value)));
if(bad){if(!err){err=document.createElement('span');err.className='field-error';err.id='err-'+k;el.insertAdjacentElement('afterend',err);el.addEventListener('input',()=>{el.removeAttribute('aria-invalid');el.removeAttribute('aria-describedby');err.remove()},{once:true})}
err.textContent=msg;el.setAttribute('aria-invalid','true');el.setAttribute('aria-describedby',err.id);first=first||el}else{el.removeAttribute('aria-invalid');el.removeAttribute('aria-describedby');err&&err.remove()}});
const st=document.querySelector('#form-status');if(first){st.textContent='Please fix the highlighted fields.';st.style.color='var(--danger)';first.focus();return false}st.style.color='';return true}
document.querySelector('#brief')?.setAttribute('novalidate','');

document.querySelector('#brief button[type=submit]')?.removeAttribute('disabled');
